### ISSUE TITLE
[Solved] Campaign map generation

### ISSUE THREAD

**Issue by Acidello** [pan324/anno1800_seedfinder#1]
Hey @pan324,

Thanks for publishing this powerful resource! I have been searching for such a tool for a long time and I am glad someone has finally reproduced the algorhythm of seed generation.
I also have a very stupid question, feel free to ignore if you are busy with stuff...

Does Campaign map generation use a different algorhythm? Because I was just testing out the script with Archipelago settings, hoping that it somehow affected Campaign seeds (as they're forced on Archipelago) but as I assume they just work differently. Typing seed numbers suggested by the script in Campaign generates often some rivers on both OW and CT, and doesn't give the wanted islands.
I suppose that having forced island models (referring to Ditchwater, Bright Sands, La Isla and Prosperity) on both OW and NW affects the whole algorhythm? Not asking if you found out how it works, but just a curiosity to know your opinion since you put your hands on the formula already.
Big thanks again!

Acidello

**Comment by pan324** [comment]
I had not looked into this before because the campaign is rather short and enforces a lot. This being said, let us dive into this.

1) The campaign has only limited settings. Archipelago is enforced, as well as map size. We can also check the templates.csv in the repo. The template of interest is 
data/sessions/maps/campaign/moderate/campaign_chapter01_moderate_01/campaign_chapter01_moderate_01.a7t
which is the same regardless of the IslandSize setting. So the user selection here has no effect on the old world. There is also a column "Campaign" which marks the template. The code has to check that column for selection. This column is a bit silly because everywhere else in the game, this gamemode is basically multiple-choice-like bitmask but only here it works differently.
=> To choose the right template, we need to select the right settings: Archipelago Large and (to be implemented) set gamemode to CampaignMode.
2) Some islands are not available in campaign mode. Check the raw.csv or the various other csvs in the islands folder.
In particular, L2,L2R and L7,L7R are not available in campaign. Currently the gamemode is just hardcoded but if a gamemode variable is introduced as needed in 1), this step is automatically solved as well.
3) The baseline data is worthless. The baseline is literally just a list of all seeds without rivers for that maptype, mapsize, islandsize. Once again, this is missing the gamemode information, so the tool will happily use the existing baseline even though it needs to be recreated. 
4) The preplaced islands come before the normal island distribution. They do not interact with the island slots or islands in any way. Thankfully, they do not even draw rotation (which would affect the RNG). This requires no code change at all.

Because there are very few large islands, the number of seeds without rivers is huge, so it requires some more filtering than just removing rivers. When I exclude L3 L5 and M1 from the baseline, I get 26156112 for large island optimization, 582037998 for large+medium island optimization and 1185713575 for large+medium+small island optimization.

I will clean up the code a bit and probably push it later today.

**Comment by Acidello** [comment]
Wow! Thank you so much for such a quick and precise answer!

**Comment by pan324** [comment]
The change is now live. The code does not enforce game settings like selecting the campaign in the game does. So you need to select the right map type and map size yourself or it will just complain about not finding any templates.

**Comment by Acidello** [comment]
Thank you!
