### ISSUE TITLE
Questions about Rivers 

### ISSUE THREAD

**Issue by Nebelwacht** [pan324/anno1800_seedfinder#3]
Heyho, 
I hope that's the correct place for it, but i am not sure... never used github before, beside just downloading stuff ^^

First of all: Thanks so much for that great tool! Since years i was waiting for such a tool that i can use to just search for "legit" seeds... And i'm really really happy that finally there is a tool like that =D 
Spend a few hours yesterday to figure out how to use it probably after it was recommended on the anno 1800 discord. I managed to get some decent results, but some things i just can't figure out. Even asked someone else to have a look as well, but we both couldn't get satisfying results, so i was wondering if you may could help me understanding your system a bit better? :x 

So my questions/problems are: 
In general i don't know how the river filter works:
1) How can i add Islands WITH rivers into a map? E.g. L7R and L11R... no matter what i'm doing... if i delete them in the "unwantedbaseline", if i add them in the "wantedold" or if i delete the ## in the score category and set their score to 99999.... i just can't get them to spawn consistently. 
2) I don't want a map without rivers, but i still was wondering why the seedfinder still generates maps with rivers on medium islands? I thought its optimised to filter those out in general? Or are there medium islands that have more buildable area with a river, compared to other medium islands without a river, so that river islands still get a higher score overall? 
3) Just out of interesst; Can you tell me where those "no/low river" baseline is added? And if its possible to avoid that "no river" filter and purely filter on combined island score?  I thought its in the "unwantedbaseline" ff area, but i think i was wrong :x 

Btw. i have to say that i have absolutely no clue about programming, so i probably won't understand many details xD 

Again, thanks so much for this amazing tool! I can't wait for it to get the attention it deserves! =D

**Comment by pan324** [comment]
As for github, you and me both. (I have a couple repos on bitbucket though.)

1. The seed finder will use existing baselines even when the settings have changed. You must manually delete the file in the "seeds" folder to actually start a new baseline search on the same map. These files right now are basically just txt files of every single seed in the game without river.
2. Yup, the scores/tiles are directly given in the code and can be customized. We can see that M5R is much better than M1 or M9.
3. It's possible to filter on island scores, but at the moment a baseline is always needed. The baseline supports filtering by score, so you can start with a low score value (e.g. 480000 when including all islands), start a baseline search, and abort if the baseline has more than ~100k hits. Then increase the score threshold a bit and try again until you get less than 100k hits. That baseline can then be used. The codebase was not exactly designed with this kind of approach in mind, mainly because I did not expect the code to be as fast as it is. (I expected pre-filtering on good and bad islands to be absolutely mandatory to get results in time.) Beware: The baseline filtering on scores instead of unwanted islands takes about 4 times as long (10 min on 16 cores).

Regarding 1, it's a bit of a leftover from early development where baseline results were written as soon as the finder began, which destroyed the baseline. It was rather easy to mess up and at some point I was tired of waiting for the baseline to be recreated. A proper fix would mean adding the full scoring scheme and wanted and unwanted islands at the top of each file to make sure that the desired setting has not been tried yet. Not too hard to pull off, actually.

**Comment by pan324** [comment]
I have added a small example how to do filtering, right after the other example.

**Comment by Nebelwacht** [comment]
Thanks for the fast reply =D 
Spend 4+ hours on trying to make it work, but really couldn't figure it out.
I deleted the seed files and tried setting those parameters: 
unwanted = ""
wantedold = "L7R L11R L2R L5R L1 L4 CIR L3"
wantedcape = "L1 L7 L13 M8 M7R M3R"
I played around with the "minscorebaseline =" setting then, trying to limit it to a decent result, but could't work it out

Then i changed it and tried putting the islands in the baseline section:
unwantedbaseline = ""
wantedbaselineold = "L7R L11R L2R L5R L1 L4 CIR L3"
wantedbaselinecape = "L1 L7 L13 M8 M7R M3R"
minscorebaseline = -1e30 
It created a decent baseline (i think) cut couldn't find any seeds... 

Mhh, need to play around with it a bit more when i come back from work xD

**Comment by Nebelwacht** [comment]
Heyho its me again.
Played a bit more with it and got some decent results. But i still wonder why i get so small amounts of results. 

e.g. with:
unwantedbaseline = ""
wantedbaselineold = "L7R L11R L2R L5R L1 L4 L3"
wantedbaselinecape = "L1 L7 L13 M8 M3R"
minscorebaseline = -1e30  # Baseline must have this score at least. Leave this at -1e30 to not filter by score.

(**map: Arc**, everything else wasn't changed)
--> With those settings, after deleting the baseline entries, i only get 2 new baseline maps. Is it really realistic, that there are only 2 results that match those island combination in that huge amount of random maps? Or is there a filter working in the background, that i haven't figured out jet?

**Comment by pan324** [comment]
Seems about right. For the old world, you want to pick 7 islands out of a pool of 25 (given 8 slots for large islands). For the cape world, you want to pick 3 islands out of a pool of 25 (given 3 slots) and 2 islands out of a pool of 15 (given 6 slots). This kind of behavior is described by the hypergeometric distribution.

```
from scipy.stats import hypergeom as gm
gm.pmf(7, 25, 7 ,8) * gm.pmf(3,25,3,3) * gm.pmf(2,15,2,6)
# This yields 1.033689223919047e-09
```
So the odds are one in a billion and there are only 2 billion seeds to check, so this exactly matches expectations.

**Comment by Nebelwacht** [comment]
meh, should have done the math before myself. Well, it had a reason why i went into biotechnology direction and away from math xD 
Thanks again for all the help and this amazing tool =D
