### ISSUE TITLE
Hard Difficulty Islands

### ISSUE THREAD

**Issue by Moozipan** [pan324/anno1800_seedfinder#5]
Hi, I was curious if it's possible to filter islands with "hard" difficulty yet, to get some rivers on the map.

The tool is working great for me with the default settings and some custom ones, as long as I leave the difficulty setting on "normal". If I change that setting to "hard", I always get zero seeds as a result. I played with a few other settings, but maybe it's not possible to do that at all in the current build, so I figured I'd rather ask.

Thanks for all the time you put into this, it has already proven to be very useful!

**Comment by pan324** [comment]
You probably need to be careful around the filtering conditions you set. Basically the code is still a bit dumb (proper parallelization would be quite a lot bigger), but we can do some semi-manual optimization. The section Example - Filter by Score roughly goes through the steps.

So first of all, take care that your selection does not already exist in the seeds folder. Otherwise, delete that file. Next, in the main.py I added a couple of special cases at lines of 140-160 which might mess with your own settings. Remove those lines if they interfere with your selections.

Now finally, on large maps there exist no world without rivers which is why nothing is found. If you only care about size but not rivers (we don't really have much of a choice here), set unwantedbaseline = "" to include river islands in the calculations.

Now set minscorebaseline to some positive value to threshold the results. The code always needs to do a baseline scan so we need to filter by score. The score is the sum of all island tiles by default, but the islands themselves are not random, so a good threshold is a bit hard to get. The code could probably figure out the worst and best case actually, but it's not implemented. 

Anyway, set minscorebaseline to e.g. 100000 at first (large islands are ~30000 tiles each) and run the code. You should get feedback about the progress and that all seeds are being considered. Stop with ctrl+c and Increase to 150000 and try again. Then maybe 200000 and then 220000, until the estimated seeds goes below 100000. I took the cheapest parallelization so the reporting back is directly coupled to the number of accepted seeds, so the higher you go the less feedback you get. Once the estimated number of seeds is below 100000, let the baseline scan finish. It will then directly proceed with the refinement which just sorts all these seeds by score so you can check out the best of the best.

**Comment by Moozipan** [comment]
Ah I finally got it, your explanation has been extremely helpful. I wasn't so much interested in island size with maximum tiles, but more in getting a seed with my preferred islands in terms of looks (and placement) on the map, including a quick preview instead of testing seeds ingame one by one with long loading times and all. I like to have at least some rivers, so now that this is resolved it's working perfectly for me! Thanks again <3
