### ISSUE TITLE
Additional filtering of new world islands 

### ISSUE THREAD

**Issue by christianhopfner** [pan324/anno1800_seedfinder#6]
Hey, first of all I appreciate your great tool really like it.

I wonder how to extend the search engine arguments to be able to filter seeds especially for small maps. Since the new world size and therefore island count is reduced, additional new wolrd filters would be cool.

What i think i comprehended so far is that the score map inside main.py needs an extension with the new world score, therefore short naming needs adaption right? After that additional arguments like baselines using the BinarizeWorld/Island need to be added as well. Afterall the findseed.cpp->find() needs an extension for new world island region.

Do I miss something major here? I'm not a python expert but consider to improve my skillset

**Comment by pan324** [comment]
Short names already exist for all worlds, e.g. small islands: https://github.com/pan324/anno1800_seedfinder/blob/main/islands/small.csv The lists just need updating for the latest DLC.

The util.py also already has a LoadNewWorld which loads the new world islands just fine. The visualize.py right now already shows the new world without issues. So we really just need to binarize the new world templates and islands and then hand them over.

The main adjustment needed is that step 2 from the notes needs updating in the cpp. I haven't checked the latest game update, but in the previous versions there were three worlds/templates for the new world. The first random number to draw would decide this. The cpp needs to be handed 5 worlds in total due to this and two sets of islands. It might make sense to streamline the argument passing a bit because it is already quite cumbersome. Otherwise the parameters would change from

    Island* small, int nsmall, Island* medium, int nmedium, Island* large, int nlarge,
    Slot* slotsold, int a, int b, int c, int d, 
    Slot* slotcape, int e, int f, int g, int h,

to something like

    Island* small, int nsmall, Island* medium, int nmedium, Island* large, int nlarge,
    Island* small2, int nsmall2, Island* medium2, int nmedium2, Island* large2, int nlarge2,
    Slot* slotsold, int a, int b, int c, int d, 
    Slot* slotcape, int e, int f, int g, int h,
    Slot* slotsnew, int i, int j, int k, int l, 
    Slot* slotnew2, int m, int n, int o, int p,
    Slot* slotnew3, int q, int r, int s, int t,

where we hand a second set of (new world) islands and then the three new templates, which is actually still okay for a quick fix.

**Comment by christianhopfner** [comment]
oh yeah I stumpled over the /islands/size.csv but wondered why short name are identical for moderate and colony. That made me thinking we need other short names. But from your explanation it I get your idea of just create a second score {} for newworld islands.
I meanwhile tried to extend the map visualization with the larger newworld. I had some difficulties so far. I had to adapt some asserts and search function within mapstocsv since the newer templates haven't been pulled 


```
def CreateXmls():
...
found[newname] = path
#try:
#    assert newname not in found
#except AssertionError as e:
#    print(e)
#else:
#    found[newname] = path
```

and later on since there are new elements in the xml dom but only for new islands
```
mp = root[0]
obj = Map()

# assert set([elem.tag for elem in mp]) == {'TemplateElement', 'RandomlyPlacedThirdParties', 'Size', 'PlayableArea', 'ElementCount'}
```

getislandtiles.py is difficult as well because they changed the whole definition of build areas which are divided into smaller blocks now for the new islands therefore the [val] tag is gone ...

I currently have at least a seedfinder which shows the updated new world with all its islands before new world was incorrect and reduced in island count

**Comment by pan324** [comment]
I did actually measure tiles of nonriver islands manually ingame because the game does way too much processing on the raw data. Only for the river islands I did it automatically by subtracting file values from the nonriver islands values. This subtracts slightly too much for river islands but given that rivers have some difficult tiles it should be fairly balanced still.

I have finished updating the finder and will push it once I have measured the tiles.

**Comment by christianhopfner** [comment]
sounds great if you need a helping hand for specific islands let me know

**Comment by pan324** [comment]
You are totally right, the files are completely crazy for the river tiles. On the bright side the manually measured values are more accurate anyway. I have just finished measuring them all.

I just want to streamline/simplify the interface a bit more and will push tomorrow.
